title: iAlicornio
subtitle: "Another place, another way."
description: "Description has been omitted."
keywords: []
author: Universe
language: zh-CN

url: https://ial.pages.dev/
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: false 
  trailing_html: false 

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: records
category_dir: categories
code_dir: ""
i18n_dir: :lang
skip_render:

new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: -date
default_category: uncategorized
category_map:
tag_map:
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

theme: volantis-tweaked

deploy:
  type: ''

timezone: ''
include:
exclude:
per_page: 10
pagination_dir: page
ignore:
